---
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
  become: yes

- name: Join node to Kubernetes control plane.
  shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  tags: ["skip_ansible_lint"]
